# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'libpyscl\resources\pyside\main.ui'
#
# Created: Sat Aug 19 21:46:13 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 663)
        self.widget = QtGui.QWidget(MainWindow)
        self.widget.setEnabled(True)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tbw_attr = QtGui.QTableWidget(self.tab)
        self.tbw_attr.setObjectName("tbw_attr")
        self.tbw_attr.setColumnCount(0)
        self.tbw_attr.setRowCount(0)
        self.gridLayout_4.addWidget(self.tbw_attr, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.trw_nodes = QtGui.QTreeWidget(self.tab)
        self.trw_nodes.setObjectName("trw_nodes")
        self.gridLayout_3.addWidget(self.trw_nodes, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.cb_loglvl = QtGui.QComboBox(self.widget)
        self.cb_loglvl.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cb_loglvl.setObjectName("cb_loglvl")
        self.cb_loglvl.addItem("")
        self.cb_loglvl.addItem("")
        self.cb_loglvl.addItem("")
        self.cb_loglvl.addItem("")
        self.cb_loglvl.addItem("")
        self.cb_loglvl.addItem("")
        self.verticalLayout.addWidget(self.cb_loglvl)
        self.pte_status = QtGui.QPlainTextEdit(self.widget)
        self.pte_status.setMaximumSize(QtCore.QSize(16777215, 150))
        self.pte_status.setReadOnly(True)
        self.pte_status.setObjectName("pte_status")
        self.verticalLayout.addWidget(self.pte_status)
        MainWindow.setCentralWidget(self.widget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 787, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.a_open = QtGui.QAction(MainWindow)
        self.a_open.setObjectName("a_open")
        self.a_save = QtGui.QAction(MainWindow)
        self.a_save.setObjectName("a_save")
        self.a_close = QtGui.QAction(MainWindow)
        self.a_close.setObjectName("a_close")
        self.a_about = QtGui.QAction(MainWindow)
        self.a_about.setObjectName("a_about")
        self.a_saveas = QtGui.QAction(MainWindow)
        self.a_saveas.setObjectName("a_saveas")
        self.a_clean = QtGui.QAction(MainWindow)
        self.a_clean.setObjectName("a_clean")
        self.menuFile.addAction(self.a_open)
        self.menuFile.addAction(self.a_save)
        self.menuFile.addAction(self.a_saveas)
        self.menuFile.addAction(self.a_close)
        self.menuHelp.addAction(self.a_about)
        self.menuEdit.addAction(self.a_clean)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "PySCL", None, QtGui.QApplication.UnicodeUTF8))
        self.trw_nodes.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "SCL", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Node View", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Logging Level</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setItemText(0, QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setItemText(1, QtGui.QApplication.translate("MainWindow", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setItemText(2, QtGui.QApplication.translate("MainWindow", "Warning", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setItemText(3, QtGui.QApplication.translate("MainWindow", "Error", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setItemText(4, QtGui.QApplication.translate("MainWindow", "Critical", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_loglvl.setItemText(5, QtGui.QApplication.translate("MainWindow", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.a_open.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.a_save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.a_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.a_about.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.a_saveas.setText(QtGui.QApplication.translate("MainWindow", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.a_clean.setText(QtGui.QApplication.translate("MainWindow", "Clean", None, QtGui.QApplication.UnicodeUTF8))

